version: '3.8'
services:
  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_USER: user 
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    networks:
      - ecommerce-net 
  user-service:
    build: .
    container_name: user-service 
    ports: 
      - "8081:8081"
    depends_on:
      - user-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/userdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: admin123
    networks:
      - ecommerce-net 
    
networks:
  ecommerce-net:

volumes: 
  postgres_data:
