server:
  port: 8081 #? Each server has its own port

spring:
  application:
    name: user-service
  
  datasource:
    url: jdbc:postgresql://user-db:5432/user-db
    username: user
    password: admin123
    driver-class-name: org.postgresql.Driver 

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect 
    hibernate:
      ddl-auto: update #? only for dev
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
jwt:
  secret: PZmV+RkTyYcbXHM2Bp9/lDGN8h/y0+dpdrdSPeRcY1w=
  expiration: 86400000 #? 1 day in ms